ls: cannot access /tmp/x509up_u101050: No such file or directory
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-requests/2.21.0-pafccj2/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
----- Begin Fatal Exception 17-Mar-2023 14:37:30 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /afs/cern.ch/work/e/elfontan/private/DiPhotonAnalysis/Anna_Legacy2018/CMSSW_10_6_8/src/flashgg/Systematics/test/outdir_Legacy18_testULvsLegacy_newLabel/workspaceStd.py
Exception Message:
 unknown python problem occurred.
ValueError: invalid literal for int() with base 0: ''

At:
  /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_8/python/FWCore/ParameterSet/VarParsing.py(518): _convert
  /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_8/python/FWCore/ParameterSet/VarParsing.py(464): setDefault
  /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_8/python/FWCore/ParameterSet/VarParsing.py(214): parseArguments
  /afs/cern.ch/work/e/elfontan/private/DiPhotonAnalysis/Anna_Legacy2018/CMSSW_10_6_8/python/flashgg/MetaData/JobConfig.py(500): parse
  /afs/cern.ch/work/e/elfontan/private/DiPhotonAnalysis/Anna_Legacy2018/CMSSW_10_6_8/src/flashgg/Systematics/test/outdir_Legacy18_testULvsLegacy_newLabel/workspaceStd.py(205): <module>

----- End Fatal Exception -------------------------------------------------
